version: "3.9"
services:
  jobflowr-api:
    build: .
    image: jobflowr-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  jobflowr-react:
    build: ./react-js
    image: jobflowr-react
    ports:
      - "8000:3000"
    depends_on:
      - jobflowr-api
    volumes:
      - ./react-js:/app
