version: "3.9"
services:
  jobflowr-api:
    build: .
    image: jobflowr-api
    ports:
      - "3000:3000"

  jobflowr-react:
    build:
      context: .
      dockerfile: react-js/Dockerfile
    image: jobflowr-react
    ports:
      - "8000:3000"
