default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: djonyreinert
development:
  <<: *default
  database: jobflowr_development
test:
  <<: *default
  database: jobflowr_test
production:
  <<: *default
  database: jobflowr_production
  username: jobflowr
  password: <%= ENV['JOBFLOWR_DATABASE_PASSWORD'] %>
